### PR TITLE
Hostprocess blog

### PR DESCRIPTION
**Pull request by kunal-kushwaha**
cc @brasmith-ms

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
This PR changes 2 articles. Is that right?

**Comment by kunal-kushwaha** [comment]
> This PR changes 2 articles. Is that right?

Hmm it should only have 'Windows HostProcess Container Blog' I believe.

**Comment by brasmith-ms** [comment]
Hi @kunal-kushwaha the content for this should be all set now.

**Comment by kunal-kushwaha** [comment]
Thanks @brasmith-ms!

**Pull request merged**
